### ISSUE TITLE
Latest releases are not being published to npm

### ISSUE THREAD

**Issue by vtsatskin** [creditkarma/thrift-typescript#122]
The [latest version on npm is 2.0.0](https://www.npmjs.com/package/@creditkarma/thrift-typescript). However there is a release for 2.0.3 on github.

Investigating this a little bit, seems like [something broke in CI](https://circleci.com/gh/creditkarma/thrift-typescript/419?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

**Comment by kevin-greene-ck** [comment]
Resolved, latest version published to `npm`
