### ISSUE TITLE
Falling back to java namespace

### ISSUE THREAD

**Issue by TobiasBales** [creditkarma/thrift-typescript#131]
I am currently in the works of writing a service to generate thrift clients and for that to work I'd ideally need to have an empty js namespace. We do need to set the java namespace though so currently [this](https://github.com/creditkarma/thrift-typescript/blob/786542d5e7da27b56c17d1bed2a59c87ab219470/src/main/resolver/utils.ts#L25) is biting us.

Is it an option to remove the fallback (as the comment suggest). Otherwise I'd set out to make it configurable I think

**Comment by kevinbgreene** [comment]
I’d rather it be configurable as it would be a breaking change for people and I don’t want a major version bump just for this. We can change default behavior in the next major release.

**Comment by kevin-greene-ck** [comment]
@TobiasBales don't know if you've started doing anything to this. But I'm going to work on it this morning and get something out. I'll add an option `--fallback-namespace` that will default to "java" but you will be able to set it to an empty string.

**Comment by TobiasBales** [comment]
@kevin-greene-ck thanks for that, hadn't started because I am currently doing a couple other related thrift things when time permits.

Unrelated but is a release for `thrift-server` planned?

**Comment by kevin-greene-ck** [comment]
@TobiasBales I'll get a release out today. Actually this change should also make it into a release today.
