### ISSUE TITLE
Validation error when referencing existing variables such as defined strings in set<string>

### ISSUE THREAD

**Issue by augbog** [creditkarma/thrift-typescript#138]
I get validation errors when referencing defined `strings` such as in a `set<string>`. For example if I had a Example.thrift file

```
const string MIME_TYPE_GIF = "image/gif";
const string MIME_TYPE_JPEG = "image/jpeg";

const set<string> MIME_TYPES = [
  MIME_TYPE_GIF,
  MIME_TYPE_JPEG
];
```
I would get the error

```
Validation Error:

Message: Expected type string but found type MIME_TYPE_GIF

5 |   MIME_TYPE_GIF,
```

However setting actual strings in the `set<string>` works fine.

**Comment by hayes** [comment]
I am also running into this issue.

Temporary workaround for us is to not use `const` and just inline the strings.

**Comment by kevin-greene-ck** [comment]
A fix for this is coming. A little backed up, looking at a week or two before it makes a release.

**Comment by hayes** [comment]
that's awesome! thanks for the update.

**Comment by hayes** [comment]
Is this actively being worked on/in progress, or just on your roadmap? I have some time today, and could probably fix it.

**Comment by kevin-greene-ck** [comment]
@hayes Yeah, I've got a fix working for this and will have it up in the next day or two. Thanks.
