### ISSUE TITLE
Why do strict unions require thrift-server?

### ISSUE THREAD

**Issue by NinoScript** [creditkarma/thrift-typescript#147]
I only want to use it for code generation for a web client, currently using `--target apache`.
What does using `--target thrift-server` imply?
Can it be used on a browser if I don't use the server features?

**Comment by kevin-greene-ck** [comment]
`thrift-server` is a collection of packages that are our version of the apache core libraries (https://github.com/creditkarma/thrift-server). It has a client (@creditkarma/thrift-client) as well, but won't work in the browser without providing a polyfill for Node's `Buffer` object and creating a custom `Connection` object to work with `XHR` or `fetch`.

It's on the roadmap to add browser support, but not there now. In terms of why, the strict unions types fit in well with how we were splitting up data types for the `thrift-server` target, where interfaces were the source of truth and not classes. It may not be that bad to add support for apache, but I haven't really sketched out what that would look like.

In general new features we (creditkarma team) add will be targeted to `thrift-server` and `apache` will remain TS that hues very similar to the JS that is produced by the apache code generator. We're not opposed to adding features to the `apache` codegen, but those contributions would likely need to come from the community.

**Comment by NinoScript** [comment]
That's fair, thanks for answering!

It seems we won't be using a `union` for this feature in our organization, but when we do in the future, we'll put some of our time into the `apache` codegen.
