### ISSUE TITLE
3.7.2-0 has type errors for optional fields

### ISSUE THREAD

**Issue by hayes** [creditkarma/thrift-typescript#166]
@kevin-greene-ck I did not test my change well enough.  Just did a little more testing and realized I made a bad assumption.

The underlying issue is that the args interface has optional fields, but does not accept undefined as a value:

`{ foo: undefined }` is not assignable to `{ foo?: string }`.

**Comment by kevin-greene-ck** [comment]
No worries, that's why I did a prerelease so I could run it through all our testing. Will you be able to fix or do I need to make time to look at it?

**Comment by hayes** [comment]
Still trying to fully understand the issue. I'll update in a few minutes when I have a better idea of how to fix it.

**Comment by hayes** [comment]
it looks like it may actually be related to strict unions

**Comment by hayes** [comment]
@kevin-greene-ck I think the solution is that for unions I need to change the generated code from:

`const obj: TypeName = {...};`
to
`const obj = {...} as TypeName;`

does that sound reasonable?

**Comment by hayes** [comment]
the issue was actually that it can't the compiler can't know that only one of the props is set for the unions type when its reconstructing it from the args object.

**Comment by hayes** [comment]
It would be simpler to do the same thing for both structs and unions
