### ISSUE TITLE
Add a debugger similar to thrift-parser

### ISSUE THREAD

**Issue by kevinbgreene** [creditkarma/thrift-typescript#71]
For the static analysis phases (resolver, validator) we should report errors similar to how it is being done in the parser. Don't throw on first error, collect errors and print errors with the line of source that caused the error, highlighting the problem token.

**Comment by kevin-greene-ck** [comment]
This was added with https://github.com/creditkarma/thrift-typescript/commit/5834f802bba1649fcc8aef82b109a744674891f5
