### ISSUE TITLE
Add version info to generated source

### ISSUE THREAD

**Issue by ian-harshman-ck** [creditkarma/thrift-typescript#72]
We should add a docblock header to the top of each source file so we can trace generated source back to a particular version of this tool. 

Something like:
```
/**
 * Generated by @creditkarma/thrift-typescript
 * Version 0.0.2
 */
```

**Comment by kevin-greene-ck** [comment]
Added: https://github.com/creditkarma/thrift-typescript/commit/e5dd0b0a024846b1ab4b6afc0377ec9a4b10492b
