### ISSUE TITLE
Services cannot return promises

### ISSUE THREAD

**Issue by ian-harshman-ck** [creditkarma/thrift-typescript#75]
I'll use this simple service for reference.
```
service MyService {
   Response call(1: Request request)
}
```

In this case, the tool generates something like
```
export interface IMyServiceHandler<Context> {
    call: (request: Request, context: Context) => Response;
}
```

Notice that the return type does not allow for promises to be returned. I believe we can make the return type `Response | Promise<Response>` as a non-breaking change.

**Comment by kevinbgreene** [comment]
I was fixing this while you were filing this https://github.com/creditkarma/thrift-typescript/commit/1f19526843e58a7552465ce1f061e16d2020464a
